### ISSUE TITLE
How to override styling dropdown for searchable component??

### ISSUE THREAD

**Issue by aRhez0903** [asantibanez/livewire-select#30]

**Comment by leobeal** [comment]
You can only override the `styles()` method from the parent component class.

**Comment by Luigi-DV** [comment]
### In order to manage the views in our project and as a consequence the style of each one, we need to follow the steps below:

- [ ] Publish the views:

  ` php artisan vendor:publish       `
- [ ] This show a list like this:

   _Which provider or tag's files would you like to publish?:
  [0 ] Publish files from all providers and tags listed below
  [1 ] Provider: Asantibanez\LivewireSelect\LivewireSelectServiceProvider ..._

- [ ] Select the provider **Asantibanez\LivewireSelect\LivewireSelectServiceProvider**

- [ ] Go to r**esources/views/vendor/livewire-select** and change the components class


Hope my simple solution works for your project :)
